config/routes.rb
Themultiverse::Application.routes.draw do
  devise_for :users

  root :to=> "home#index"

  resources :users do
    resources :friends
    resources :cards do
      resources :comments
    end
  end
  resources :cards do
    resources :comments
  end
  resources :sets, :as=>:card_sets do
    resources :comments
    resources :cards do
      resources :comments
    end
    resources :slots, :as=>:card_slots
  end
  

end

app/controllers/sets_controller.rb
class SetsController < ApplicationController
  before_filter :find_set, :only=>[:show,:edit,:update,:destroy]
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :ensure_editor_permissionship!, :only => [:edit, :update, :destroy]
  before_filter :ensure_viewing_permissionship!, :only => [:show]
  
  respond_to :html, :xml, :json
  
  def index
    respond_with(@sets = CardSet.all)
  end
  
  def show
    respond_with @set
  end
  
  def new
    @set = CardSet.new
    respond_with @set
  end
  
  def create
    @set = CardSet.new(params[:card_set])
    @set.save
    @set.add_editor current_user
    respond_with @set
  end
  
  def edit
    respond_with @set
  end
  
  def update
    #check for new card slots
    for_param(:card_set,:new_slots) do |new_slots|
      @set.add_slots new_slots.to_i
    end
    
    #check for cutting cards
    for_param(:card_set,:cut_card) do |cut_card|
      @set.cut_card cut_card
    end
    
    #check for resubmitting cards
    for_param(:card_set,:resubmit_card) do |resubmitted_card|
      @set.resubmit_card resubmitted_card
    end
    
    @set.update_attributes(params[:card_set])
    respond_with @set
  end
  
  def destroy
    @set.destroy
    respond_with @set, :location=>sets_path
  end
  
  protected
  def find_set
    @set = CardSet.find(params[:id])
    if @set.nil?
      redirect_to sets_path
    end
  end
  
  def ensure_editor_permissionship!
    unless @set.can_edit? current_user
      logger.info "insufficient editing permissions"
      redirect_to root_path
    end
  end
  
  def ensure_viewing_permissionship!
    unless @set.can_view? current_user
      logger.info "insufficent viewing permissions"
      redirect_to root_path
    end
  end
  
end

app/views/sets/_a_add_slots.html.haml
=form_for set do |f|
  =f.text_field :new_slots, :value=>'', :placeholder=>'number of slots to add'
  =f.submit 'add card slots', :class=>:action

app/views/sets/_a_cut_card.html.haml
=form_for [card.owner,card] do |f|
  =f.hidden_field :cut, :value=>card.id
  =f.submit 'cut me', :class=>:action

app/views/sets/_a_edit_card.html.haml
=link_to 'edit me',url_for([card.owner,card])+'/edit', :class=>:action

app/views/sets/_a_edit_slots.html.haml
=link_to "edit slots", url_for(set)+'/slots', :class=>:action

app/views/sets/_a_new_card.html.haml
=link_to "submit a new card", new_card_set_card_path(set), :class=>:action

app/views/sets/_a_resubmit_card.html.haml
=form_for [card.owner,card] do |f|
  =f.hidden_field :submit, :value=>card.id
  =f.submit 'resubmit me', :class=>:action

app/views/sets/_a_unslot_card.html.haml
=form_for [card.owner,card] do |f|
  =f.hidden_field :submit, :value=>card.id
  =f.submit 'unslot me', :class=>:action

app/views/sets/_a_view_card.html.haml
=link_to 'view me',[card.owner,card], :class=>:action

app/views/sets/new.html.haml
%section.cardset
  %header<
    %h1 New Set
  =form_for @set do |f|
    =f.text_field :name
    =f.submit

app/views/sets/show.html.haml
%section.cardset
  %header<
    %h1=  @set.name
  %section.submitted.card_section.source
    %header<
      %h1 submitted
    =render :partial=>'shared/actions', :locals=>{:actions=>[{:partial=>'sets/new_card',:locals=>{:set=>@set}}]}
    -for card in @set.cards.submitted
      %article.set_card.source
        =render :partial=>'cards/physical', :locals=>{:card=>card}
        =render :partial=>'shared/actions', :locals=>{:actions=>[{:partial=>'sets/cut_card',:locals=>{:card=>card}},
          {:partial=>'sets/view_card',:locals=>{:set=>@set,:card=>card}},
          {:partial=>'sets/edit_card',:locals=>{:set=>@set,:card=>card}}]}
  %section.slotted.card_section.source
    %header<
      %h1 slotted
    =render :partial=>'shared/actions', :locals=>{:actions=>[{:partial=>'sets/edit_slots',:locals=>{:set=>@set}},
      {:partial=>'sets/add_slots',:locals=>{:set=>@set}}]}
    -for slot in @set.card_slots
      =render :partial=>'slots/slot', :locals=>{:slot=>slot,:card_actions=>[{:partial=>'sets/cut_card',:locals=>{}},
        {:partial=>'sets/unslot_card',:locals=>{:card=>card}},
        {:partial=>'sets/view_card',:locals=>{:card=>card}},
        {:partial=>'sets/edit_card',:locals=>{:card=>card}}],
        :slot_actions=>[{:partial=>'slots/fill_slot',:locals=>{:slot=>slot}}]}
  %section.cut.card_section.source
    %header<
      %h1 cut
    -for card in @set.cards.cut
      %article.set_card.source
        =render :partial=>'cards/physical', :locals=>{:card=>card}
        =render :partial=>'shared/actions', :locals=>{:actions=>[{:partial=>'sets/resubmit_card',:locals=>{:card=>card}},
          {:partial=>'sets/view_card',:locals=>{:card=>card}},
          {:partial=>'sets/edit_card',:locals=>{:card=>card}}]}