config/routes.rb
Themultiverse::Application.routes.draw do
  devise_for :users

  root :to=> "home#index"

  resources :users do
    resources :friends
    resources :cards do
      resources :comments
    end
  end
  resources :cards do
    resources :comments
  end
  resources :sets, :as=>:card_sets do
    resources :comments
    resources :cards do
      resources :comments
    end
    resources :slots, :as=>:card_slots
  end
  

end

app/models/Card.rb
class Card
  include Mongoid::Document
  field :title
  field :cost
  field :type
  field :picture
  field :rarity
  field :ability
  field :flavor_text
  field :power
  field :toughness
  field :status
  field :favor
  
  field :slot
  
  referenced_in :user
  embeds_many :comments
  embeds_many :alterations
  embedded_in :owner, :inverse_of=>:card
  
  scope :submitted, where(:status=>'submitted')
  scope :slotted, where(:status=>'slotted')
  scope :cut, where(:status=>'cut')
  
  before_update :register_changes
  
  def slot
    slot_id = read_attribute :slot
    owner.card_slots.find(slot_id)
  end
  
  def slot= the_slot
    if the_slot.nil?
      write_attribute :slot,nil
    else
      write_attribute :slot,the_slot.id
    end
  end
  
  def unslot_card
    the_slot = slot
    unless the_slot.nil?
      the_slot.remove_card self
      slot = nil
    end
  end
  
  def set_status new_status
    unslot_card
    write_attribute :status,new_status
  end
  
  def slot_card the_slot
    set_status 'slotted'
    write_attribute :slot,the_slot.id
    the_slot.add_card self
  end
  
  def submit_card
    set_status 'submitted'
  end
  
  def cut_card
    set_status 'cut'
  end
  
  def updater= last_updater
    @updater = last_updater
  end
  
  def updater
    @updater
  end
  
  def register_changes
    Alteration.save_changes(self,@updater)
  end
  
  def editor_permissions? the_user
    if the_user == user
      return true
    else
      return false
    end
  end
  
  def viewer_permissions? the_user
    return true
  end
  
  def events
    result = comments + alterations
    result.sort!{|a,b|a.created_at<=>b.created_at}
  end
  
  def get_frame
    frame = ''
    colors = {'w'=>'white','u'=>'blue','b'=>'black','r'=>'red','g'=>'green'}
    if self.cost
      self.cost.each_char do |c|
        color = colors[c.downcase]
        if color
          if frame == '' or frame == color
            frame = color
          else
            frame = 'multicolor'
          end
        end
      end
    end
    if frame == ''
      if self.type.downcase.include? 'land'
        return 'land'
      end
      if self.type.downcase.include? 'artifact'
        return 'artifact'
      end
      return 'purple'
    end
    return frame
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_owner
  before_filter :find_card, :only=>[:show,:edit,:update,:destroy]
  before_filter :ensure_editor_permissionship!, :only => [:edit, :update, :destroy]
  before_filter :ensure_viewing_permissionship!, :only => [:show]
  
  respond_to :html, :xml, :json
  
  def index
    logger.info "making it to Cards#index"
    if @parents[0].nil?
      respond_with(@cards = [])
    else
      respond_with(@cards = @parents[0].cards)
    end
  end
  
  def show
    respond_with @card
  end
  
  def new
    @card = Card.new
    respond_with @card
  end
  
  def create
    @card = Card.new(params[:card])
    @card.user = current_user
    @card.updater = current_user
    @parents[0].add_card @card
    @card.save
    respond_with @card, :location=>@parents[0]
  end
  
  def edit
    respond_with @card
  end
  
  def update
    @card.updater = current_user
    
    for_param(:card,:submit) do
      @card.submit_card
      @card.save
    end
    
    for_param(:card,:cut) do
      @card.cut_card
      @card.save
    end
    
    for_param(:card,:slot) do |slot_id|
      slot = @card.owner.card_slots.find(slot_id)
      @card.slot_card slot
      @card.save
    end
    
    @card.attributes = params[:card]
    @card.save
    respond_with @card, :location=>@card.owner
  end
  
  def destroy
    @card.destroy
    respond_with @card, :location=>@parents.reverse
  end
  
  protected
  
  def find_owner
    if @parents[0].nil?
      if user_signed_in?
        @parents[0] = current_user
      else
        logger.info("owner not found")
        redirect_to root_path
      end
    end
  end
  
  def find_card
    collection = @parents[0].cards
    @card = collection.find(params[:id])
    if @card.nil?
      logger.info("card not found in #{@parents[0].inspect}")
      redirect_to root_path
    end
  end
  
  def ensure_editor_permissionship!
    if !@card.editor_permissions? current_user
      logger.info("insufficient editing permissions")
      redirect_to root_path, :alert=>"you don't have permission to do that"
    end
  end
  
  def ensure_viewing_permissionship!
    if !@card.viewer_permissions? current_user
      logger.info("insufficient viewing permissions")
      redirect_to root_path, :alert=>"this card is private"
    end
  end
  
end

app/views/cards/_a_edit.html.haml
= button_to( 'make some changes', edit_card_path(card), :method=>:get, :class=>:action)

app/views/cards/_a_other_cards.html.haml
=button_to( 'other cards', cards_path, :method=>:get, :class=>:action)

app/views/cards/_a_trash.html.haml
=button_to( 'trash this card', card, :method=>:delete, :class=>:action)

app/views/cards/_form.html.haml
= form_for(@card, :url=>url_for(@parents.reverse.push(@card))) do |f|
  - if @card.errors.any?
    %section.errorExplanation
      %header<
        %h1= pluralize(@card.errors.count, 'error') + " kept this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg
  
  .title.field
    =f.label :title
    =f.text_field :title
  
  .cost.field
    =f.label :cost
    =f.text_field :cost
  
  .type.field
    =f.label :type
    =f.text_field :type
  
  .rarity.field
    =f.label :rarity
    =f.text_field :rarity
  
  .ability.field
    =f.label :ability
    =f.text_area :ability
  
  .flavor_text.field
    =f.label :flavor_text
    =f.text_area :flavor_text

  .power.field
    =f.label :power
    =f.text_field :power

  .toughness.field
    =f.label :toughness
    =f.text_field :toughness
  
  .actions
    =f.submit

app/views/cards/_physical.html.haml
%section.physical{:class=>card.get_frame}
  %h1
    .title= card.title or ""
    -if card.cost
      .cost= card.cost
  .picture
    -if card.picture
      %img{:src=>card.picture.source}
  .type= card.type
  .ability_box
    -if card.ability
      -card.ability.split("\r\n").each do |ability|
        .ability= ability
    -if card.flavor_text
      .flavor_text=card.flavor_text
  -if card.power and card.power != "" and card.toughness and card.toughness != ""
    .power.toughness
      %p= "#{card.power}/#{card.toughness}"
  -elsif card.favor
    .favor
      %p=card.favor

app/views/cards/edit.html.haml
%section.editcard
  %header<
    %h1 Edit Card
  =render 'form'

app/views/cards/index.html.haml
%section.cardlist
  %header<
    %h1 Card List
  %ul
    -@cards.each do |card|
      %li= link_to card.title,card
  %footer
    -if @parents and !@parents.empty?
      =link_to 'new card',url_for(@parents.reverse)+'/cards/new'
    -else
      =link_to 'new card',new_card_path

app/views/cards/new.html.haml
%section.newcard
  %header<
    %h1 New Card
  =render 'form'

app/views/cards/show.html.haml
%article.magicCard
  %header<
    %h1= @card.title
    .wrapper.source
      =render :partial=>"physical", :locals=>{:card=>@card}
      -actions = [{:partial=>'cards/other_cards',:locals=>{}}]
      -if user_signed_in?
        -if @card.editor_permissions?( current_user)
          -actions.unshift( {:partial=>'cards/trash',:locals=>{:card=>@card}})
          -actions.unshift( {:partial=>'cards/edit',:locals=>{:card=>@card}})
      =render :partial=>"shared/actions",:locals=>{:actions=>actions}
  -if user_signed_in?
    =render :partial=>'shared/shared_block', :locals=>{:user=>current_user,:type=>'new_comment',:object=>Array.new(@parents).reverse.push(@card), :callback=>'comments/new_comment'}
  =render :partial=>'events/event_list', :locals=>{:events=>@card.events}
-if @card.owner.class == CardSet
  -for slot in @card.owner.card_slots
    %article.slot
      =render :partial=>'slots/slot', :locals=>{:slot=>slot,:card_actions=>[],:slot_actions=>[{:partial=>'slots/fill_slot_with_card',:locals=>{:slot=>slot,:card=>@card}}]}